### ISSUE TITLE
Extension effectively freezing browser tab on some sites

### ISSUE THREAD

**Issue by ai212983** [mooltipass/extension#108]
Navigate to http://echo.msk.ru, watch tab freeze for 30+ seconds.

It seems problem is in `mcCombinations.prototype.detectSubmitButton`.  Filtering function includes elements cloning, which is expensive. If submit button is not detected in given container, it is recursively called on its parent, repeating the filtering and expensive cloning.

![Call Tree for detectSubmitButton](https://user-images.githubusercontent.com/87319/128178774-d3fc505c-2276-41bf-bc4a-c35a1b3103a4.png)

![Bottom-Up for cloneNode in detectSubmitButton](https://user-images.githubusercontent.com/87319/128179367-e3b06bc0-8f30-4e35-ae47-485bd5b5a4d7.png)

**Comment by limpkin** [comment]
hello,
wow, thanks for the great report! our extension developer will tackle it after his current task :)

**Comment by limpkin** [comment]
fixed by #116

**Comment by limpkin** [comment]
beta version 1.9.10 with this fix is about to be released for chome at https://chrome.google.com/webstore/detail/mooltipass-extension/mkjlelalgdinanmcljpgkojjolkdcebh?hl=en&authuser=0 , could you give it a go?

**Comment by ai212983** [comment]
@limpkin Awesome, looks really good so far, thanks!

I guess this issue is resolved for me with 1.10.0.
