### ISSUE TITLE
The extension's "GitHub source" link points to original Mooltipass App not the extension

### ISSUE THREAD

**Issue by spoelstraethan** [mooltipass/extension#123]
https://github.com/mooltipass/extension/blob/8476ef61d64fa9c27cb22661b3bb6fe8d7bb9207/options/about.html#L39

This makes it almost impossible for people that don't know GitHub to know how to look at @limpkin 's profile and recent commits to get over to the mooltipass org and the extension/moolticute/etc repositories where this really lives.

**Comment by limpkin** [comment]
nice catch!! thanks :)
