### ISSUE TITLE
Feature request: detect if firefox or chrome password managers are enabled

### ISSUE THREAD

**Issue by limpkin** [mooltipass/extension#14]
... and offer the user to disable it

**Comment by Daroosh** [comment]
In Chrome, we could offer the user to disable it via the browser notifications.
In Firefox, buttons are still not supported in notifications. How would we handle it? Should we enforce the disabling and simply display a notifications informing the user that we have disabled the default password manager?

**Comment by limpkin** [comment]
the more I think about this one the more I think we should display a quick tutorial at extension first install. In it we would detect the browser and explain how to disable the password manager

**Comment by jaeheonshim** [comment]
Working on it! :)

**Comment by limpkin** [comment]
implemented
