### ISSUE TITLE
Extra character after login and password

### ISSUE THREAD

**Issue by astuder** [mooltipass/extension#144]
Not sure if this is a bug in the browser extension, or the newly updated Moolticute.

I updated Moolticute today, and since today I get an extra trailing character (0x00?) in the login and password fields.

![extra-character](https://user-images.githubusercontent.com/1166488/204438060-eb668c5f-235a-4d04-87ca-458750ca3bd1.png)

Device: Mooltipass Mini 1.0
Moolticute: v1.00.0 (updated today)
Mooltipass Extension: 1.10.10
Browser: Firefox 107.0
OS: Windows 11

**Comment by astuder** [comment]
PS: When manually removing the trailing characters, I get a "Credentials Detected" notification from Moolticute, but not prompt on the Mooltipass Mini screen.

**Comment by limpkin** [comment]
wow that's a bit worrying... do you get that for every single website or just one in particular?

**Comment by limpkin** [comment]
what's your windows locale? We're getting other reports and are trying to find the common configuration between them :)

**Comment by astuder** [comment]
US english

**Comment by limpkin** [comment]
were these credentials imported through csv import?

**Comment by astuder** [comment]
No. Just credentials I collected via Mooltipass over the years. Unless the update of Moolticute did it behind the scene during the update and backup, I didn't update or reimport the credentials in the device.

**Comment by limpkin** [comment]
would you be able to enable debug logs, restart moolticute, try to login and send me the logs at support(at)themooltipass(dot)com? Please switch passwords after sending me the logs :)

Thanks!

**Comment by limpkin** [comment]
@astuder ! we've just released 1.00.1 at https://github.com/mooltipass/moolticute/releases .. could you give it a quick go and let us know if things improved?

**Comment by astuder** [comment]
Yes, that fixed the issue. Thanks for the quick turnaround!

**Comment by limpkin** [comment]
awesome!
