### ISSUE TITLE
Passwords repeated when device disconnected

### ISSUE THREAD

**Issue by EugeneRymarev** [mooltipass/extension#155]
When generating passwords, they are repeated every time the same, as if they were coming from the list in order.
![image](https://user-images.githubusercontent.com/6260309/233779434-5d97cb82-5297-453c-b2d2-9a450c4fd67c.png)
![image](https://user-images.githubusercontent.com/6260309/233779442-7fd171f8-e65b-4d48-bda3-03767d182658.png)
![image](https://user-images.githubusercontent.com/6260309/233779448-5bb66690-945a-45f0-98a1-6ae951540542.png)
And when I try to generate a password again after reloading the page, or on another site, I again see the same set of passwords in the same order.
![image](https://user-images.githubusercontent.com/6260309/233779499-8c34d78b-e457-439a-bf06-f78c8c2dc685.png)

Details in Element #mooltipass chat.

**Comment by limpkin** [comment]
is this happening **only when the device is disconnected**?

**Comment by EugeneRymarev** [comment]
@limpkin, yes. All fine when device connected.

**Comment by limpkin** [comment]
we're now preventing password generation when no device is connected
