### ISSUE TITLE
[Bug] No text shown in password generator (Linux Firefox)

### ISSUE THREAD

**Issue by hijackeel** [mooltipass/extension#161]
When I click the key symbol on a page's password field, the "Password Generator" field in the extension's pop-up does not show any text. This started happening some time back, I think after a Firefox update. I'm currently on Firefox version 119.0.1 (Linux), and Extension version 1.10.13.

**Comment by limpkin** [comment]
hello! that usually happens when no device is detected. does native credential recall still work for you?

**Comment by hijackeel** [comment]
Hey, it's working for me again now. I think it was a Firefox issue because there was another plug-in that had also stopped working properly for me but is working again now. I'm currently on Firefox 120.0.1.
