### ISSUE TITLE
Password Generator not working

### ISSUE THREAD

**Issue by awilkins** [mooltipass/extension#165]
Firefox 122.0.1
Ubuntu 20.04

- Click the key icon in a sign-up form for which there are no existing creds
- Password box is blank.
- Click "Re-generate"
- Nothing happens

Seeing the following in debug console - but not closely associated with clicking the action link. No obvious stack dumps from clicking anything.

```
Error: Promised response from onMessage listener went out of scope 14 [init.js:38:34](moz-extension://5c8a47cd-1f37-4796-b3be-7681ecf25c75/background/init.js)
```

```js
/**
     * Generate information structure for created tab and invoke all needed
     * functions if tab is created in foreground
     * @param {object} tab
     */

        chrome.runtime.onMessage.addListener(mooltipassEvent.onMessage);  // <--- THIS LINE

        chrome.tabs.onCreated.addListener(function (tab) {
            if (tab.id > 0) {
                if (tab.selected) {
                    page.currentTabId = tab.id;
                    event.invoke(page.switchTab, null, tab.id, []);
                }
            }
        });
```

## Workaround

Generate a password manually.

**Comment by limpkin** [comment]
is the device connected to the computer when this happens?

**Comment by awilkins** [comment]
Device is connected via Bluetooth ; connecting to USB doesn't immediately fix this though.

**Comment by limpkin** [comment]
damn I thought I had answered this... is this still happening?
