### ISSUE TITLE
Credentials save/recall when login is split into 2 forms

### ISSUE THREAD

**Issue by nekromant** [mooltipass/extension#167]
This is not very common, but a local ISP has a weird login form that seems to breaks things:

![Screenshot_20240808_111147](https://github.com/user-attachments/assets/8bf9a0aa-e44e-46e7-94c4-f1582b0fa7b0)

The login (your account number) is split in two numbers. Right now the extension can only handle and remember one of them as the login.

**Comment by limpkin** [comment]
that's an odd one indeed... can you report it using the extension menu? that's how we know about problematic websites

**Comment by nekromant** [comment]
Will do!
