### ISSUE TITLE
Mooltipass Extension for Chrome not available anymore

### ISSUE THREAD

**Issue by Scooty66** [mooltipass/extension#170]
Hi all,

Mooltipass Extension for Chrome is not available anymore in the Chrome Webstore showing the follng message (translated from German):
This extension is no longer available because it does not follow Chrome extension best practices.

The message incliudes a link to
https://support.google.com/chrome_webstore/answer/2664769?hl=en#unsupported_extensions
for further information.

Any chance for remediation?

Andreas

**Comment by limpkin** [comment]
Oh wow, it seems google is really pushing for everyone to not use werequestblocking anymore...  
we'll push our beta testing version to our main channel: https://chromewebstore.google.com/detail/mooltipass-extension/mkjlelalgdinanmcljpgkojjolkdcebh

**Comment by limpkin** [comment]
in which country are you located in? It's still available for me :)

**Comment by Scooty66** [comment]
Hi, I am located in Germany.

**Comment by limpkin** [comment]
I'm wondering how they're doing their rollout... I might still hold out for a few days...

**Comment by Scooty66** [comment]
Was able to install extension Version 1.11.0 and it does seem to do the job.
Thanks for the swift reaction.
