### ISSUE TITLE
Password stored in DOM longer than necessary

### ISSUE THREAD

**Issue by c4lc** [mooltipass/extension#52]
# Issue
The Mooltipass extension asks the password daemon for authorization. Once the authorization is given via the Mooltipass device, the password is securely transferred to the Chrome extension. However, on e.g. Ajax websites like pizza.de or lieferando.de I observed, the password is stored in the website DOM until the website is reloaded or a redirect happens. This does not happen on Ajax pages and on these sites it is possible to logout and login later again even after unplugging or locking the Mooltipass device. 

# Expected behavior
Password should not be present anywhere on the computer after login was successful. The memory should be overwritten and on each login the extension should request authorization from the Mooltipass device again. Only that way a secure storage of the password is ensured.

# Steps to reproduce
1. Login to pizza.de via Mooltipass
2. Unplug or lock the device
3. Logout of the page
4. Login to the page again (the credentials will still be autofilled, as the username and password are still on the DOM / (Heap of memory)
5. After refreshing the website with F5 the password is no longer autofilled and sent.

**Comment by limpkin** [comment]
Hello,

The reasoning behind that decision is explained here: https://github.com/mooltipass/extension/tree/master/documentation#credential-caching.  
@Daroosh : Last time we talked about that, we agreed that it wasn't causing such a security risk given it was limited to a given "tab opened session". I guess what we could do is add an extra field to the credential request that specifies if the password field is detected when parsing the page, and if this flag is sent empty the credential cache?

**Comment by H8to** [comment]
Maybe a timeout should be implemented e.g. 30 seconds. Tab lifetime could be indefinite for servers and always-on computers. I'm not sure if looking for the password field is safe in terms of pages that always send you some kind of password field on each request as part of the website template (but hidden).

**Comment by limpkin** [comment]
i like that.

**Comment by limpkin** [comment]
implemented
