### ISSUE TITLE
Incorrect keyboard layout

### ISSUE THREAD

**Issue by mpble** [mooltipass/extension#80]
Entered credentials on a system using german keyboard.
xxx.yyy@domain.com
When having Mooltipass minible insert the username it enters xxx.yyy"domain.com
All settings left to standard (in Moolticute and Mooltipass mineble as well).
After changing the keyboard setting (USB) to German the inserted username changes to xxx.yyy«domain.com.

**Comment by limpkin** [comment]
Are you using a Mac? If so I still need to add these keyboards

**Comment by mpble** [comment]
Hi, 
yes, I’m using a Mac ;) On Windows 10 it seems to work.

Br
Andy

> Am 16.11.2019 um 21:10 schrieb Mathieu <notifications@github.com>:
> 
> Are you using a Mac? If so I still need to add these keyboards
>

**Comment by limpkin** [comment]
keyboards added, and duplicate issue with the one on moolticute
