### ISSUE TITLE
Updating with Moolticute 0.42.20 fails under MacOS Catalina

### ISSUE THREAD

**Issue by mpble** [mooltipass/extension#85]
I wanted to update from Aux MCU minor 9 and Main MCU minor 9.
Regardless of the bundle, I use (bundle V10 or bundle V11), I get the error „Upload finished with errors.“

I tried first updating with an older version of Moolticute (0.42.9 Catalina), then Moolticute (0.42.20, Windows10 and 0.42.20 Catalina)

**Comment by limpkin** [comment]
hello,
please create an issue in this repository: https://github.com/mooltipass/moolticute/issues

**Comment by mpble** [comment]
Darn, I forgot to insert the card backwards. I works, when I insert the card in the backward manner. Sorry.
