### ISSUE TITLE
Password generator is not configurable

### ISSUE THREAD

**Issue by gmarcusm** [mooltipass/extension#98]
The password generator of the extension is not configurable. There is no option to adjust length or valid characters to be used for a new password field.

**Comment by limpkin** [comment]
I'm fairly sure there is: go to the extension menu, click on "settings"

**Comment by gmarcusm** [comment]
oh, sorry I was not clear enough. This works for a meaningful default but not for specific websites. 

But this is not usable in practice, when a user needs to adjust it for a particular website that imposes restrictions. This would mean go to settings, change the defaults, generate a new password, save it, and go back and restore the defaults. 

The defaults is also missing a configurable set of special symbols. Some websites allow only a very specific subset.

The one size fits all fails when the user needs a specific setting once. A setting per site would be nice but might not be practical to implement (needs to save it on the mooltipass...).

It would be much more user friendly if the extension had the password settings in a expandable section above or below the generated password field, so length and complexity could be tweaked directly, and those settings would simply reset to the defaults upon leaving the website (or when arriving at a new site).
